language: cpp

os: linux
dist: trusty

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
  - echo ${PATH}
  - ${CXX} --version

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
      - george-edison55-trusty-backports
    packages:
      - cmake
      - cmake-data
      - gcc-7
      - g++-7
      - clang-5.0

compiler:
  - clang
  - gcc

env:
  matrix:
    - DCMAKE_BUILD_TYPE=Debug BUILD_DIR=build_debug
    - DCMAKE_BUILD_TYPE=Release BUILD_DIR=build_release

script:
  - mkdir -p build
  - cd build
  - cmake .. && make -j
  - test/keva-test

notifications:
  email: false