language: cpp

sudo: false
dist: trusty
osx_image: xcode9.2

notifications:
  email: false

matrix:
  include:
    # Linux + clang + debug
    - os: linux
      addons: &clang5
        apt:
          sources:
          - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libc++-dev
            - libc++abi-dev
      env: DCMAKE_BUILD_TYPE=Debug
      compiler: clang

    # Linux + clang + release
    - os: linux
      addons: *clang5
      env: DCMAKE_BUILD_TYPE=Release
      compiler: clang

    # Linux + GCC + debug
    - os: linux
      addons: &gcc7
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: DCMAKE_BUILD_TYPE=Debug
      compiler: gcc

    # Linux + GCC + release
    - os: linux
      addons: *gcc7
      env: DCMAKE_BUILD_TYPE=Release
      compiler: gcc

    # Linux + clang + debug + asan + ubsan
    - os: linux
      addons: *clang5
      env: DCMAKE_BUILD_TYPE=Debug DENABLE_SANITIZE=ON
      compiler: clang

    # Linux + clang + release + asan + ubsan
    - os: linux
      addons: *clang5
      env: DCMAKE_BUILD_TYPE=Release DENABLE_SANITIZE=ON
      compiler: clang

    # OSX + apple-clang + debug
    - os: osx
      compiler: clang
      env: DCMAKE_BUILD_TYPE=Debug

    # OSX + apple-clang + release
    - os: osx
      compiler: clang
      env: DCMAKE_BUILD_TYPE=Release

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir -p build && cd build
  - cmake .. && make -j VERBOSE=1
  - cmake --build . --target all
  - ./test/keva-test


install:
  - if [[ $CXX = g++ ]]; then export CXX="g++-7" CC="gcc-7"; fi
  - ${CXX} --version
