language: cpp

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- echo ${PATH}
- ${CXX} --version

compiler:
  - clang
  - gcc

env:
  matrix:
    - DCMAKE_BUILD_TYPE=Debug BUILD_DIR=build_debug
    - DCMAKE_BUILD_TYPE=Release BUILD_DIR=build_release

script:
  - mkdir -p build
  - cd build
  - cmake .. && make
  - test/keva-test

notifications:
  email: false