language: cpp

os: linux
dist: trusty

compiler:
  - clang
  - gcc

env:
  matrix:
    - DCMAKE_BUILD_TYPE=Debug BUILD_DIR=build_debug
    - DCMAKE_BUILD_TYPE=Release BUILD_DIR=build_release

script:
  - mkdir -p build
  - cd build
  - cmake .. && make
  - test/keva-test

notifications:
  email: false