#language: cpp
#
#sudo: false
#dist: trusty
#osx_image: xcode9.2
#
#install:
##  - if [[ $CXX = g++ ]]; then export CXX="g++-7" CC="gcc-7"; fi
##  - if [[ $CXX = clang++ ]]; then export CXX="clang++-5.0" CC="clang-5.0"; fi
#  - ${CXX} --version
#
#matrix:
#  include:
#    # Linux + clang + debug
#    - os: linux
##      addons:
##        apt:
##          sources:
##          - ubuntu-toolchain-r-test
##          - llvm-toolchain-trusty-5.0
##          packages:
##            - clang-5.0
#      env: DCMAKE_BUILD_TYPE=Debug #COMPILER=clang++5.0 #DCMAKE_C_COMPILER=clang-5 DCMAKE_CXX_COMPILER=clang++-5
#      compiler: clang
#
##    # Linux + clang + release
##    - os: linux
##      addons:
##        apt:
##          sources:
##            - ubuntu-toolchain-r-test
##            - llvm-toolchain-trusty-5.0
##          packages:
##            - clang-5.0
##      env: DCMAKE_BUILD_TYPE=Release
##      compiler: clang
##
##    # Linux + GCC + debug
##    - os: linux
##      addons:
##        apt:
##          sources:
##            - ubuntu-toolchain-r-test
##          packages:
##            - g++-7
##      env: DCMAKE_BUILD_TYPE=Debug
##      compiler: gcc
##
##    # Linux + GCC + release
##    - os: linux
##      addons:
##        apt:
##          sources:
##            - ubuntu-toolchain-r-test
##          packages:
##            - g++-7
##      env: DCMAKE_BUILD_TYPE=Release
##      compiler: gcc
##
##    # Linux + clang + release + asan + ubsan
##    - os: linux
##      addons:
##        apt:
##          sources:
##            - ubuntu-toolchain-r-test
##            - llvm-toolchain-trusty-5.0
##          packages:
##            - clang-5.0
##      env: DCMAKE_BUILD_TYPE=Release DENABLE_SANITIZE=ON
##      compiler: clang
##
##    # Linux + clang + debug + asan + ubsan
##    - os: linux
##      addons:
##        apt:
##          sources:
##            - ubuntu-toolchain-r-test
##            - llvm-toolchain-trusty-5.0
##          packages:
##            - clang-5.0
##      env: DCMAKE_BUILD_TYPE=Debug DENABLE_SANITIZE=ON
##      compiler: clang
##
##    # OSX + apple-clang + debug
##    - os: osx
##      compiler: clang
##      env: DCMAKE_BUILD_TYPE=Debug
##
##    # OSX + apple-clang + release
##    - os: osx
##      compiler: clang
##      env: DCMAKE_BUILD_TYPE=Release
#
#
#script:
#  - mkdir -p build
#  - cd build
#  - cmake .. make -j
#  - cmake --build . --target all
#  - ./test/keva-test
#
#notifications:
#  email: false

language: cpp

sudo: false
dist: trusty
osx_image: xcode9.2

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- echo ${PATH}
- ${CXX} --version

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0
    - george-edison55-trusty-backports
    packages:
    - cmake
    - cmake-data
    - gcc-5
    - g++-5
    - clang-5.0
    - cppcheck

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  matrix:
    - CMAKE_CONFIGURATION=release BUILD_DIR=build_release
    - CMAKE_CONFIGURATION=debug BUILD_DIR=build_debug

matrix:
  exclude:
  - os: osx
    compiler: gcc

script:
  - mkdir build
  - cd build
  - cmake .. && make
  - cmake --build . --target all

notifications:
  email: false
